[package]
name = "server"
version = "0.1.0"
authors = ["Frankie Bagnardi <f.bagnardi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = { version = "3.3", default-features = false }
anyhow = "1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
nanoid = "0.4"
env_logger = "0.8"
# chrono = "0.4"
